// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using family_tree_builder.Data;

#nullable disable

namespace family_tree_builder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122221115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("family_tree_builder.Models.PersonNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Fid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Pids")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PersonNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
